---
metadata:                           # mandatory
  version: 2.4
hosts:                              # each of the element of the topology_configs file is optional, but once provided we validate whether mandatory params are provided
- name: sut                      # mandatory
  instantiate: true                 # mandatory - determines whether Host object should be instantiated when using fixture
  role: sut                         # mandatory
  network_interfaces:               # optional
  - interface_name: {{ sut_adapter }}
    ips:
    - value: 192.168.1.1
      mask: 24
    - value: fec0::2:101
      mask: 112  # 1 of 5 (interface_name, pci_address, pci_device, speed, family) acceptable network interface identifier
  connections:                      # optional
  - ip_address: {{ sut_mng_address }}
    connection_type: RPyCConnection
- name: client
  instantiate: true
  role: client
  network_interfaces:
  - interface_name: {{ client_adapter }}
    ips:
    - value: 192.168.1.2
      mask: 24
    - value: fec0::2:102
      mask: 112  # 1 of
  connections:
  - ip_address: {{ client_mng_address }}
    connection_type: RPyCConnection